### ISSUE TITLE
   Proceso de negocio

### ISSUE THREAD

**Issue by Aylin67** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-equipo-ija#1]
[PRACTICA5.pdf](https://github.com/user-attachments/files/17123931/PRACTICA5.pdf)

**Comment by Luisangelriverosbautista** [comment]
19 a mi parecer cumplieron con la mayoria de lo requerido

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
